
import "../globals.css";
import Link from "next/link";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const style = {
    backgroundColor: "blue ",
    color: "white",
    fontSize: "0.8rem",
    padding: 10,
    cursor: "pointer",
    border: "none",
    borderRadius: "9px",
  };
  return (

      <div>
        <div className="link">
          <Link href="/assignment-1">
            <button style={style}>Assignment Day 1</button>
          </Link>
        </div>
        <div className="link">
          <Link href="/">
            <button style={style}>Home</button>
          </Link>
          <Link href="/assignment-1/question-1">
            <button style={style}>Question 1</button>
          </Link>
          <Link href="/assignment-1/question-2">
            <button style={style}>Question 2</button>
          </Link>
          <Link href="/assignment-1/question-3">
            <button style={style}>Question 3</button>
          </Link>
          <Link href="/assignment-1/question-4">
            <button style={style}>Question 4</button>
          </Link>
          <Link href="/assignment-1/question-5">
            <button style={style}>Question 5</button>
          </Link>
          <Link href="/assignment-1/question-6">
            <button style={style}>Question 6</button>
          </Link>
        </div>
        {children}
      </div>
  );
}
